name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

      