# Simple workflow for deploying static content to GitHub Pages
name: Build and Test 

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows other workflows to invoke this
  workflow_call:

jobs:
  deploy:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/test